package pokemon;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author jeani
 */
public class TelaPokemon extends javax.swing.JFrame {

    /**
     * Creates new form TelaPokemon
     */
    public TelaPokemon() {
        initComponents();

        ImageIcon image = new ImageIcon(getClass().getResource("Charmander.png"));
        lblImagem1.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImagem1.getWidth(), lblImagem1.getHeight(), Image.SCALE_DEFAULT)));

        ImageIcon image2 = new ImageIcon(getClass().getResource("Charmander.png"));
        lblImagem2.setIcon(new ImageIcon(image2.getImage().getScaledInstance(lblImagem2.getWidth(), lblImagem2.getHeight(), Image.SCALE_DEFAULT)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxPokemon1 = new javax.swing.JComboBox<>();
        cbxPokemon2 = new javax.swing.JComboBox<>();
        lblImagem2 = new javax.swing.JLabel();
        lblImagem1 = new javax.swing.JLabel();
        batalha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("                                                                     Escolha seu Pokemon");
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Escolha seu Pokemon:");

        jLabel2.setText("Escolha o Pokemon do Adversário:");

        cbxPokemon1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Charmander", "Bulbasauro", "Squirtle", "Geodude" }));
        cbxPokemon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPokemon1ActionPerformed(evt);
            }
        });

        cbxPokemon2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Charmander", "Bulbasauro", "Squirtle", "Geodude" }));
        cbxPokemon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPokemon2ActionPerformed(evt);
            }
        });

        lblImagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/Bulbasauro.png"))); // NOI18N

        lblImagem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/Charmander.png"))); // NOI18N

        batalha.setText("Batalhar!");
        batalha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxPokemon1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagem1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagem2)
                    .addComponent(cbxPokemon2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(batalha, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxPokemon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxPokemon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagem2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblImagem1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(batalha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxPokemon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPokemon1ActionPerformed
        if (cbxPokemon1.getSelectedIndex() == 0) {
            ImageIcon image2 = new ImageIcon(getClass().getResource("Charmander.png"));
            lblImagem1.setIcon(new ImageIcon(image2.getImage().getScaledInstance(lblImagem1.getWidth(), lblImagem1.getHeight(), Image.SCALE_DEFAULT)));

        }

        if (cbxPokemon1.getSelectedIndex() == 1) {
            ImageIcon image = new ImageIcon(getClass().getResource("Bulbasauro.png"));
            lblImagem1.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImagem1.getWidth(), lblImagem1.getHeight(), Image.SCALE_DEFAULT)));

        }

        if (cbxPokemon1.getSelectedIndex() == 2) {
            ImageIcon image = new ImageIcon(getClass().getResource("Squirtle.png"));
            lblImagem1.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImagem1.getWidth(), lblImagem1.getHeight(), Image.SCALE_DEFAULT)));

        }

        if (cbxPokemon1.getSelectedIndex() == 3) {
            ImageIcon image = new ImageIcon(getClass().getResource("Geodude.png"));
            lblImagem1.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImagem1.getWidth(), lblImagem1.getHeight(), Image.SCALE_DEFAULT)));

        }

    }//GEN-LAST:event_cbxPokemon1ActionPerformed

    private void cbxPokemon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPokemon2ActionPerformed
        if (cbxPokemon2.getSelectedIndex() == 0) {
            ImageIcon image2 = new ImageIcon(getClass().getResource("Charmander.png"));
            lblImagem2.setIcon(new ImageIcon(image2.getImage().getScaledInstance(lblImagem1.getWidth(), lblImagem1.getHeight(), Image.SCALE_DEFAULT)));

        }

        if (cbxPokemon2.getSelectedIndex() == 1) {
            ImageIcon image = new ImageIcon(getClass().getResource("Bulbasauro.png"));
            lblImagem2.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImagem1.getWidth(), lblImagem1.getHeight(), Image.SCALE_DEFAULT)));

        }

        if (cbxPokemon2.getSelectedIndex() == 2) {
            ImageIcon image = new ImageIcon(getClass().getResource("Squirtle.png"));
            lblImagem2.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImagem1.getWidth(), lblImagem1.getHeight(), Image.SCALE_DEFAULT)));

        }

        if (cbxPokemon2.getSelectedIndex() == 3) {
            ImageIcon image = new ImageIcon(getClass().getResource("Geodude.png"));
            lblImagem2.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImagem1.getWidth(), lblImagem1.getHeight(), Image.SCALE_DEFAULT)));

        }

    }//GEN-LAST:event_cbxPokemon2ActionPerformed

    private void batalhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalhaActionPerformed

        if (cbxPokemon1.getSelectedIndex() == 0 && cbxPokemon2.getSelectedIndex() == 0) {
            Pokemon meuPokemon = new Pokemon("Charmander", "Fogo");
            meuPokemon.imprimePokemon();

            Pokemon outroPokemon = new Pokemon("Charmander", "Fogo");
            outroPokemon.imprimePokemon();

            Batalha batalha = new Batalha();
            batalha.meuPokemon(meuPokemon.getNome(), meuPokemon.getVida());
            batalha.outroPokemon(outroPokemon.getNome(), outroPokemon.getVida());

            batalha.startBattle();

        }

        if (cbxPokemon1.getSelectedIndex() == 0 && cbxPokemon2.getSelectedIndex() == 1) {
            Pokemon meuPokemon = new Pokemon("Charmander", "Fogo");
            meuPokemon.imprimePokemon();

            Pokemon outroPokemon = new Pokemon("Bulbasauro", "Planta");
            outroPokemon.imprimePokemon();

            Batalha batalha = new Batalha();
            batalha.meuPokemon(meuPokemon.getNome(), meuPokemon.getVida());
            batalha.outroPokemon(outroPokemon.getNome(), outroPokemon.getVida());

            batalha.startBattle();

        }

        if (cbxPokemon1.getSelectedIndex() == 0 && cbxPokemon2.getSelectedIndex() == 2) {
            Pokemon meuPokemon = new Pokemon("Charmander", "Fogo");
            meuPokemon.imprimePokemon();

            Pokemon outroPokemon = new Pokemon("Squirtle", "Agua");
            outroPokemon.imprimePokemon();

            Batalha batalha = new Batalha();
            batalha.meuPokemon(meuPokemon.getNome(), meuPokemon.getVida());
            batalha.outroPokemon(outroPokemon.getNome(), outroPokemon.getVida());

            batalha.startBattle();

        }

        if (cbxPokemon1.getSelectedIndex() == 0 && cbxPokemon2.getSelectedIndex() == 3) {
            Pokemon meuPokemon = new Pokemon("Charmander", "Fogo");
            meuPokemon.imprimePokemon();

            Pokemon outroPokemon = new Pokemon("Geodude", "Pedra");
            outroPokemon.imprimePokemon();

            Batalha batalha = new Batalha();
            batalha.meuPokemon(meuPokemon.getNome(), meuPokemon.getVida());
            batalha.outroPokemon(outroPokemon.getNome(), outroPokemon.getVida());

            batalha.startBattle();

        }

        if (cbxPokemon1.getSelectedIndex() == 1 && cbxPokemon2.getSelectedIndex() == 0) {
            Pokemon meuPokemon = new Pokemon("Bulbasauro", "Planta");
            meuPokemon.imprimePokemon();

            Pokemon outroPokemon = new Pokemon("Charmander", "Fogo");
            outroPokemon.imprimePokemon();

            Batalha batalha = new Batalha();
            batalha.meuPokemon(meuPokemon.getNome(), meuPokemon.getVida());
            batalha.outroPokemon(outroPokemon.getNome(), outroPokemon.getVida());

            batalha.startBattle();

        }

        if (cbxPokemon1.getSelectedIndex() == 1 && cbxPokemon2.getSelectedIndex() == 1) {
            Pokemon meuPokemon = new Pokemon("Bulbasauro", "Planta");
            meuPokemon.imprimePokemon();

            Pokemon outroPokemon = new Pokemon("Bulbasauro", "Planta");
            outroPokemon.imprimePokemon();

            Batalha batalha = new Batalha();
            batalha.meuPokemon(meuPokemon.getNome(), meuPokemon.getVida());
            batalha.outroPokemon(outroPokemon.getNome(), outroPokemon.getVida());

            batalha.startBattle();

        }

        if (cbxPokemon1.getSelectedIndex() == 1 && cbxPokemon2.getSelectedIndex() == 2) {
            Pokemon meuPokemon = new Pokemon("Bulbasauro", "Planta");
            meuPokemon.imprimePokemon();

            Pokemon outroPokemon = new Pokemon("Squirtle", "Agua");
            outroPokemon.imprimePokemon();

            Batalha batalha = new Batalha();
            batalha.meuPokemon(meuPokemon.getNome(), meuPokemon.getVida());
            batalha.outroPokemon(outroPokemon.getNome(), outroPokemon.getVida());

            batalha.startBattle();

        }

        if (cbxPokemon1.getSelectedIndex() == 1 && cbxPokemon2.getSelectedIndex() == 3) {
            Pokemon meuPokemon = new Pokemon("Bulbasauro", "Planta");
            meuPokemon.imprimePokemon();

            Pokemon outroPokemon = new Pokemon("Geodude", "Pedra");
            outroPokemon.imprimePokemon();

            Batalha batalha = new Batalha();
            batalha.meuPokemon(meuPokemon.getNome(), meuPokemon.getVida());
            batalha.outroPokemon(outroPokemon.getNome(), outroPokemon.getVida());

            batalha.startBattle();

        }

        if (cbxPokemon1.getSelectedIndex() == 2 && cbxPokemon2.getSelectedIndex() == 0) {
            Pokemon meuPokemon = new Pokemon("Squirtle", "Agua");
            meuPokemon.imprimePokemon();

            Pokemon outroPokemon = new Pokemon("Charmander", "Fogo");
            outroPokemon.imprimePokemon();

            Batalha batalha = new Batalha();
            batalha.meuPokemon(meuPokemon.getNome(), meuPokemon.getVida());
            batalha.outroPokemon(outroPokemon.getNome(), outroPokemon.getVida());

            batalha.startBattle();

        }

        if (cbxPokemon1.getSelectedIndex() == 2 && cbxPokemon2.getSelectedIndex() == 1) {
            Pokemon meuPokemon = new Pokemon("Squirtle", "Agua");
            meuPokemon.imprimePokemon();

            Pokemon outroPokemon = new Pokemon("Bulbasauro", "Planta");
            outroPokemon.imprimePokemon();

            Batalha batalha = new Batalha();
            batalha.meuPokemon(meuPokemon.getNome(), meuPokemon.getVida());
            batalha.outroPokemon(outroPokemon.getNome(), outroPokemon.getVida());

            batalha.startBattle();

        }

        if (cbxPokemon1.getSelectedIndex() == 2 && cbxPokemon2.getSelectedIndex() == 2) {
            Pokemon meuPokemon = new Pokemon("Squirtle", "Agua");
            meuPokemon.imprimePokemon();

            Pokemon outroPokemon = new Pokemon("Squirtle", "Agua");
            outroPokemon.imprimePokemon();

            Batalha batalha = new Batalha();
            batalha.meuPokemon(meuPokemon.getNome(), meuPokemon.getVida());
            batalha.outroPokemon(outroPokemon.getNome(), outroPokemon.getVida());

            batalha.startBattle();

        }

        if (cbxPokemon1.getSelectedIndex() == 2 && cbxPokemon2.getSelectedIndex() == 3) {
            Pokemon meuPokemon = new Pokemon("Squirtle", "Agua");
            meuPokemon.imprimePokemon();

            Pokemon outroPokemon = new Pokemon("Geodude", "Pedra");
            outroPokemon.imprimePokemon();

            Batalha batalha = new Batalha();
            batalha.meuPokemon(meuPokemon.getNome(), meuPokemon.getVida());
            batalha.outroPokemon(outroPokemon.getNome(), outroPokemon.getVida());

            batalha.startBattle();

        }

        if (cbxPokemon1.getSelectedIndex() == 3 && cbxPokemon2.getSelectedIndex() == 0) {
            Pokemon meuPokemon = new Pokemon("Geodude", "Pedra");
            meuPokemon.imprimePokemon();

            Pokemon outroPokemon = new Pokemon("Charmander", "Fogo");
            outroPokemon.imprimePokemon();

            Batalha batalha = new Batalha();
            batalha.meuPokemon(meuPokemon.getNome(), meuPokemon.getVida());
            batalha.outroPokemon(outroPokemon.getNome(), outroPokemon.getVida());

            batalha.startBattle();

        }

        if (cbxPokemon1.getSelectedIndex() == 3 && cbxPokemon2.getSelectedIndex() == 1) {
            Pokemon meuPokemon = new Pokemon("Geodude", "Pedra");
            meuPokemon.imprimePokemon();

            Pokemon outroPokemon = new Pokemon("Bulbasauro", "Planta");
            outroPokemon.imprimePokemon();

            Batalha batalha = new Batalha();
            batalha.meuPokemon(meuPokemon.getNome(), meuPokemon.getVida());
            batalha.outroPokemon(outroPokemon.getNome(), outroPokemon.getVida());

            batalha.startBattle();

        }

        if (cbxPokemon1.getSelectedIndex() == 3 && cbxPokemon2.getSelectedIndex() == 2) {
            Pokemon meuPokemon = new Pokemon("Geodude", "Pedra");
            meuPokemon.imprimePokemon();

            Pokemon outroPokemon = new Pokemon("Squirtle", "Agua");
            outroPokemon.imprimePokemon();

            Batalha batalha = new Batalha();
            batalha.meuPokemon(meuPokemon.getNome(), meuPokemon.getVida());
            batalha.outroPokemon(outroPokemon.getNome(), outroPokemon.getVida());

            batalha.startBattle();

        }

        if (cbxPokemon1.getSelectedIndex() == 3 && cbxPokemon2.getSelectedIndex() == 3) {
            Pokemon meuPokemon = new Pokemon("Geodude", "Pedra");
            meuPokemon.imprimePokemon();

            Pokemon outroPokemon = new Pokemon("Geodude", "Pedra");
            outroPokemon.imprimePokemon();

            Batalha batalha = new Batalha();
            batalha.meuPokemon(meuPokemon.getNome(), meuPokemon.getVida());
            batalha.outroPokemon(outroPokemon.getNome(), outroPokemon.getVida());

            batalha.startBattle();

        }


    }//GEN-LAST:event_batalhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPokemon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batalha;
    private javax.swing.JComboBox<String> cbxPokemon1;
    private javax.swing.JComboBox<String> cbxPokemon2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblImagem1;
    private javax.swing.JLabel lblImagem2;
    // End of variables declaration//GEN-END:variables
}
